### PR TITLE
Trace analytics cypress update for 2.15

### PR DESCRIPTION
**Pull request by ps48**
### Description

* Moves trace groups to trace page
* Add service flyout test

### Issues Resolved
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1269

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ps48** [comment]
Looks like OpenSearch is not loading up due to jar hell from flow-framework:
```
Error: 6-11T15:51:40,337][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [fv-az883-120] uncaught exception in thread [main]
uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin opensearch-flow-framework due to jar hell
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:185) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0.jar:3.0.0]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104) ~[opensearch-3.0.0.jar:3.0.0]
Caused by: java.lang.IllegalStateException: failed to load plugin opensearch-flow-framework due to jar hell
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:693) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:543) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.node.Node.<init>(Node.java:499) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.node.Node.<init>(Node.java:426) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-3.0.0.jar:3.0.0]
	... 6 more
Caused by: java.lang.IllegalStateException: /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-3.0.0/plugins/opensearch-flow-framework/opensearch-flow-framework-3.0.0.0.jar requires Java 21:, your system: 14.0.2+12
	at org.opensearch.bootstrap.JarHell.checkJavaVersion(JarHell.java:278) ~[opensearch-common-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.JarHell.checkManifest(JarHell.java:251) ~[opensearch-common-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:206) ~[opensearch-common-3.0.0.jar:3.0.0]
	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:679) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:543) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:197) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.node.Node.<init>(Node.java:499) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.node.Node.<init>(Node.java:426) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-3.0.0.jar:3.0.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) ~[opensearch-3.0.0.jar:3.0.0]
	... 6 more

**Comment by ps48** [comment]
Local cypress tests runs with security: 

https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4348487/a34ae852-262e-4e90-b23c-7400628ed6ce


https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4348487/e83233b6-6a85-4b21-90a8-5f60e84ed4b7


https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4348487/c87ee5d1-f38d-4a02-91de-fcb586e2f5b6

**Comment by ps48** [comment]
@tianleh @CCongWang Can you please help review this PR and merge it in 2.x?

**Review by zhongnansu — APPROVED** [review]
lgtm

**Review by CCongWang — APPROVED** [review]

**Comment by dbwiddis** [comment]
> Looks like OpenSearch is not loading up due to jar hell from flow-framework:

Flow Framework 3.0.0 branch now uses JDK21 source/target compatibility per https://github.com/opensearch-project/OpenSearch/issues/14011

This was not backported to 2.x, so should not impact 2.15 branch.

**Pull request merged**
