### PR TITLE
[Security Plugin] Update tenant header identifiers

### PR DESCRIPTION
**Pull request by peternied**
### Description
Follow up need since the copy on these pages was modified in https://github.com/opensearch-project/security-dashboards-plugin/pull/1881

### Issues Resolved
- Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/1893

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@derek-ho Can you double check?

**Comment by peternied** [comment]
@ruanyl can you help me get this merged, it should fix our broken 2.14 integration tests.

**Review by derek-ho — APPROVED** [review]

**Review by CCongWang — APPROVED** [review]

**Comment by peternied** [comment]
@CCongWang I'm not sure what is happening with this failure, are the gradle checks broken, can you help me troubleshoot?

```
 FATAL  Error: Cannot find module '../../public/utils/constants'
Require stack:
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/plugins/notificationsDashboards/server/routes/configRoutes.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/plugins/notificationsDashboards/server/routes/index.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/plugins/notificationsDashboards/server/plugin.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/plugins/notificationsDashboards/server/index.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/plugins/plugin.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/plugins/discovery/plugins_discovery.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/plugins/discovery/index.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/plugins/plugins_service.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/plugins/index.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/index.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/cli/serve/serve.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/cli/cli.js
- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/cli/dist.js
```

**Review by Hailong-am — APPROVED** [review]

**Comment by SuZhou-Joe** [comment]
@peternied A known issue by changes from dashboards-notification and should have been solved.

**Pull request merged**
