### PR TITLE
Fixed alerting cypress tests.

### PR DESCRIPTION
**Pull request by AWSHurneyt**
### Description
Fixed cypress tests following PR https://github.com/opensearch-project/alerting/pull/1612

Please backport this PR to 2.x, and 2.13 through 2.16.

### Testing
Corresponding PR in the plugin repo that shows the tests pass with security disabled - https://github.com/opensearch-project/alerting-dashboards-plugin/pull/1027

Ran the tests on a security enabled docker domain. Had to run some test suites in chunks as they were running slow on my local machine.
Screenshot 2024-07-29 at 4 18 01 PM
Screenshot 2024-07-29 at 4 26 57 PM
Screenshot 2024-07-29 at 4 32 53 PM
Screenshot 2024-07-29 at 4 43 55 PM
Screenshot 2024-07-29 at 4 50 55 PM
Screenshot 2024-07-29 at 4 54 49 PM
Screenshot 2024-07-29 at 5 00 11 PM
Screenshot 2024-07-29 at 5 14 03 PM
Screenshot 2024-07-29 at 5 22 07 PM
Screenshot 2024-07-29 at 5 23 41 PM
Screenshot 2024-07-29 at 5 34 22 PM
Screenshot 2024-07-29 at 5 40 12 PM

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by riysaxen-amzn — APPROVED** [review]

**Comment by AWSHurneyt** [comment]
@SuZhou-Joe Actually, could you remove the 2.13-2.15 backport labels? We don't need to backport these fixes that far. Sorry!

**Comment by SuZhou-Joe** [comment]
@AWSHurneyt Sure, but the `bucket_level_monitor_spec.js` keeps failing, do you know the reason?

**Comment by AWSHurneyt** [comment]
@SuZhou-Joe 
@amsiglan ran the tests locally without security, and the screenshots above were run on a security-enabled docker image. They're passing reliably locally. Unsure what could be the difference in the PR execution.

**Comment by amsiglan** [comment]
> @SuZhou-Joe @amsiglan ran the tests locally without security, and the screenshots above were run on a security-enabled docker image. They're passing reliably locally. Unsure what could be the difference in the PR execution.

@SuZhou-Joe  I have seen in the past that CIs here fail but they are passing in our repo CIs as well as the release test passes, so I think we should be fine merging this change to unblock 2.16 and only spend time investigating if the auto cut issue is not resolved

**Comment by SuZhou-Joe** [comment]
@amsiglan @AWSHurneyt I see, I will take your manual sign-off to unblock the 2.16 release. Create an issue #1464  to track.

**Review by SuZhou-Joe — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Pull request merged**
