### PR TITLE
upgrade to 1.3.0 and use latest url

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description

Upgrade the main branch to 1.3.0 and use the `latest` url since it is ready. https://github.com/opensearch-project/opensearch-build/issues/1492

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by sichend — APPROVED** [review]

**Review by seraphjiang — APPROVED** [review]

**Comment by tianleh** [comment]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/45

**Comment by tianleh** [comment]
This Github action is using 1.3.0 Notice two failures in https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5416138784?check_suite_focus=true

@ohltyler one for AD.

@bowenlan-amzn one for ISM.

**Comment by tianleh** [comment]
> This Github action is using 1.3.0 Notice two failures in https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5416138784?check_suite_focus=true
> 
> @ohltyler one for AD.
> 
> @bowenlan-amzn one for ISM.

Could anyone from @opensearch-project/anomaly-detection check the AD failed test?

**Comment by tianleh** [comment]
cc @kavilla These errors shall be same as Jenkins job for integ test for OSD has. I am working with the related teams to address the errors.

**Comment by kavilla** [comment]
> cc @kavilla These errors shall be same as Jenkins job for integ test for OSD has. I am working with the related teams to address the errors.

\m/

**Comment by tianleh** [comment]
Let me merge in this change so that once the related teams send the PR for the fix, they can run against 1.3.0 
Also plugin teams pending onboarding can check their test status against 1.3.0

**Comment by tianleh** [comment]
> This Github action is using 1.3.0 Notice two failures in https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5416138784?check_suite_focus=true
> 
> @ohltyler one for AD.
> 
> @bowenlan-amzn one for ISM.

Since @ohltyler is on vacation, could @amitgalitz @ylwu-amzn help take a look at the AD plugin failed test case?

**Comment by amitgalitz** [comment]
> https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5416138784?check_suite_focus=true

Taking a look

**Pull request merged**
