### PR TITLE
Update workbench cypress tests for 2.0

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description

Update cypress tests for workbench to fix breaking changes from EUI and `type` removal

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamsi-amazon — APPROVED** [review]

**Review by Tengda-He — APPROVED** [review]

**Comment by joshuali925** [comment]
Not able to reproduce the CI failure, rerunning
<details>

local run passed

```
~/Projects/os-2.0/opensearch-dashboards-functional-test fix-workbench ····················································································· ✘ INT 17m 9s
❯ yarn cypress:run-without-security --spec cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
yarn run v1.22.17
$ env TZ=America/Los_Angeles NO_COLOR=1 cypress run --headless --env SECURITY_ENABLED=false --spec cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Couldn't determine Mocha version

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:      5.6.0                                                                            │
  │ Browser:      Electron 85 (headless)                                                           │
  │ Specs:        1 found (plugins/query-workbench-dashboards/ui.spec.js)                          │
  │ Searched:     cypress/integration/plugins/query-workbench-dashboards/ui.spec.js                │
  │ Experiments:  experimentalNetworkStubbing=true                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  plugins/query-workbench-dashboards/ui.spec.js                                   (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Couldn't determine Mocha version


  Dump test data
    ✓ Indexes test data for SQL and PPL (899ms)

  Test PPL UI
    ✓ Confirm results are empty (6074ms)
    ✓ Test Run button (5481ms)
    ✓ Test Clear button (7037ms)
    ✓ Test full screen view (6501ms)

  Test SQL UI
    ✓ Confirm results are empty (2939ms)
    ✓ Test Run button and field search (5795ms)
    ✓ Test Translate button (6276ms)
    ✓ Test Clear button (3243ms)
    ✓ Test full screen view (3643ms)

  Test and verify SQL downloads
    ✓ Download and verify JSON (49ms)
    ✓ Download and verify JDBC
    ✓ Download and verify CSV
    ✓ Download and verify Text

  Test table display
    ✓ Test GROUP BY (6162ms)
    ✓ Test GROUP BY with aliases and scalar function (6480ms)
    ✓ Test GROUP BY and HAVING (6606ms)
    ✓ Test ORDER BY (6445ms)
    ✓ Test JOIN (7515ms)
    ✓ Test nested fields display (7121ms)


  20 passing (1m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        20                                                                               │
  │ Passing:      20                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 28 seconds                                                             │
  │ Spec Ran:     plugins/query-workbench-dashboards/ui.spec.js                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/lijshu/Projects/os-2.0/opensearch-dashboards-functio    (9 seconds)
                          nal-test/cypress/videos/plugins/query-workbench-dashboards/
                          ui.spec.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/query-workbench-dashboards/      01:28       20       20        -        -        - │
  │    ui.spec.js                                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        01:28       20       20        -        -        -

✨  Done in 110.66s.

```

</details>

**Comment by joshuali925** [comment]
is this repo up to date? looks like github actions is using OpenSearch version 1.3.0?
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/6f68a4e2b8b4aaed2aa37e28f8feeb1c9a1505a3/.github/workflows/query-workbench-release-e2e-workflow.yml#L10-L13

**Comment by kavilla** [comment]
> is this repo up to date? looks like github actions is using OpenSearch version 1.3.0?
> 
> https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/6f68a4e2b8b4aaed2aa37e28f8feeb1c9a1505a3/.github/workflows/query-workbench-release-e2e-workflow.yml#L10-L13

we can update in that in a subsequent PR i think once we have a stable version of 2.0 if @Tengda-He  is cool with that I believe @tianleh is OOO.

**Comment by Tengda-He** [comment]
I am good then if the fix is just to switch to version 2.0

**Comment by kavilla** [comment]
> I am good then if the fix is just to switch to version 2.0

https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/189

**Pull request merged**
