### PR TITLE
Integrate prettier with eslint and apply eslint rules

### PR DESCRIPTION
**Pull request by CCongWang**
Signed-off-by: CCongWang <wangcong@umich.edu>

### Description

* Add ESLint
* Integrate prettier with ESLint
* Apply ESLint rules to project

### Issues Resolved

https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/186

### Check List

- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
added a few developers from plugin teams for visibility. cc @annie3431 here since I cannot add you to this repo as contributor.

**Comment by tianleh** [comment]
Can you rerun the failed workflow for Observability https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6167109740?check_suite_focus=true to make sure that it can succeed at least once?

**Review by Tengda-He — APPROVED** [review]

**Comment by kavilla** [comment]
> Can you rerun the failed workflow for Observability https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6167109740?check_suite_focus=true to make sure that it can succeed at least once?

@CCongWang if you rebase this and git push -f then you should get a green.

**Review by joshuali925 — APPROVED** [review]
i don't think the observability failure is a blocker for this PR, since these are only linting changes. i believe @mengweieric is tracking the flaky tests separately

**Review by seraphjiang — APPROVED** [review]

**Comment by CCongWang** [comment]
@kavilla thanks for fixing the failed tests!

**Pull request merged**
