### PR TITLE
skip flaky tests

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description

Skip frequent flaky tests https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seraphjiang — APPROVED** [review]

**Comment by kavilla** [comment]
Just to verify I think a handful of these tests, if not all, were add without previously existing? So it's safe to skip them since it just puts us in a `1.2` state?

Also, have we considered conditionally skipping them? Like a skip bad apples environment variable that only gets set in the CI (github and jenkins) [[Example PR]](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/2d44dabf01d2dfbf5990c9d16b3113ff00093335)

**Comment by tianleh** [comment]
@ohltyler how do you think from plugin perspective? Or what is your team's previous release experiences when seeing flaky Cypress tests?

**Comment by kavilla** [comment]
> I think the fundamental question is whether it is better to show the complete test result which is often failing due to flaky tests or have a success with skipped tests. @peterzhuamazon

When checking out the videos it mostly was it routed to a page and something was still initializing but the test expected it to be ready and was trying to click a button that was disabled.

**Review by davidcui1225 — COMMENTED** [review]
I don't see any panels tests in Observability failing here- how come we are skipping so many?

**Comment by tianleh** [comment]
> I don't see any panels tests in Observability failing here- how come we are skipping so many?

See https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477

**Comment by tianleh** [comment]
@davidcui1225

**Comment by tianleh** [comment]
> > @ohltyler how do you think from plugin perspective? Or what is your team's previous release experiences when seeing flaky Cypress tests?
> 
> Before, we had some known flaky tests that were skipped. As part of #95, I cleaned those up and made them much more stable. We haven't encountered many failures when running our tests in our remote integ test CI, and it succeeds the vast majority of the time. We have definitely not seen the amount of failures we're seeing listed here coming from Jenkins.
> 
> My concern is that if the Jenkins runners are so much more under-utilized than the github runners, it can lead to these unexpected high numbers of failures in the infra pipelines, since the devs are basing flakiness primarily on the github runners / CI success/failure. I'm afraid that just increasing the timeout times isn't sufficient, and can be counterproductive in that it can add a lot of time for the test suites to finish.

I have an issue in build repo to increase the Docker container memory to have a more powerful execution env. https://github.com/opensearch-project/opensearch-build/issues/1753

Since the Jenkins build is not periodic, I create multiple scheduled workflows in Github actions so that we can have enough data to see patterns. This is how I find the frequent test cases https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477

**Comment by ohltyler** [comment]
> > > @ohltyler how do you think from plugin perspective? Or what is your team's previous release experiences when seeing flaky Cypress tests?
> > 
> > 
> > Before, we had some known flaky tests that were skipped. As part of #95, I cleaned those up and made them much more stable. We haven't encountered many failures when running our tests in our remote integ test CI, and it succeeds the vast majority of the time. We have definitely not seen the amount of failures we're seeing listed here coming from Jenkins.
> > My concern is that if the Jenkins runners are so much more under-utilized than the github runners, it can lead to these unexpected high numbers of failures in the infra pipelines, since the devs are basing flakiness primarily on the github runners / CI success/failure. I'm afraid that just increasing the timeout times isn't sufficient, and can be counterproductive in that it can add a lot of time for the test suites to finish.
> 
> I have an issue in build repo to increase the Docker container memory to have a more powerful execution env. [opensearch-project/opensearch-build#1753](https://github.com/opensearch-project/opensearch-build/issues/1753)
> 
> Since the Jenkins build is not periodic, I create multiple scheduled workflows in Github actions so that we can have enough data to see patterns. This is how I find the frequent test cases [#126 (comment)](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477)

I see, so it's actually failing this much in the GitHub runner here. It's interesting how much more these seem to fail in this workflow (running all integ tests) vs. our AD workflow (running AD-only integ tests). From your [comment](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477), there's an AD failure in 8/10 runs. From our [AD workflow](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/actions/workflows/remote-integ-tests-workflow.yml), it's only failed 2 out of the last 8 runs. Granted, this is still not good and it should be more consistent, and I'll look into following up on those.

**Comment by tianleh** [comment]
> I see, so it's actually failing this much in the GitHub runner here. It's interesting how much more these seem to fail in this workflow (running all integ tests) vs. our AD workflow (running AD-only integ tests). From your [comment](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477), there's an AD failure in 8/10 runs. From our [AD workflow](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/actions/workflows/remote-integ-tests-workflow.yml), it's only failed 2 out of the last 8 runs. Granted, this is still not good and it should be more consistent, and I'll look into following up on those.

I am also tuning another parameter `numTestsKeptInMemory` in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/129/files I will keep monitoring how the schedule workflows will perform with a reduced `numTestsKeptInMemory` which is default 50 My hypothesis is that the results will be more stable and let's see the outcome.

**Review by davidcui1225 — APPROVED** [review]

**Comment by kavilla** [comment]
> I am also tuning another parameter `numTestsKeptInMemory` in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/129/files I will keep monitoring how the schedule workflows will perform with a reduced `numTestsKeptInMemory` which is default 50 My hypothesis is that the results will be more stable and let's see the outcome.

I attempted that in a couple tries and still was seeing the same behavior. I think the true issue is Jenkins + Cypress + Docker where it seems other folks have the same issue. 

I've seem other people pass --ipc=host --shm-size=512m to the docker args but was still unable to get it. [REF](https://stackoverflow.com/questions/61284940/cypress-test-failing-with-out-of-memory-error-in-docker)

**Comment by tianleh** [comment]
> I attempted that in a couple tries and still was seeing the same behavior. I think the true issue is Jenkins + Cypress + Docker where it seems other folks have the same issue.
> 
> I've seem other people pass --ipc=host --shm-size=512m to the docker args but was still unable to get it. [REF](https://stackoverflow.com/questions/61284940/cypress-test-failing-with-out-of-memory-error-in-docker).
> 
> There also might be merit to stress on the test cluster since it is a single OpenSearch so might be inadvertently stress testing OpenSearch + OpenSearch plugins.

@peterzhuamazon  We may need to try a larger memory configuration for integ test Docker on https://github.com/opensearch-project/opensearch-build/issues/1753

**Comment by peterzhuamazon** [comment]
I am against skipping these tests and would rather we fix them or expose them.
We can test the memory setup tomorrow after my dashboards integTest run complete.
Still monitoring jenkins.

Thanks.

**Review by Tengda-He — APPROVED** [review]

**Comment by tianleh** [comment]
> I am against skipping these tests and would rather we fix them or expose them. We can test the memory setup tomorrow after my dashboards integTest run complete. Still monitoring jenkins.
> 
> Thanks.

Thanks for the info! Let me convert this PR to a draft just for discussion purpose. I will create separate issues for plugin owners to fix/improve instead of skipping the flaky tests. @peterzhuamazon

**Comment by tianleh** [comment]
created a main Github issue to track the flaky tests https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/133

**Comment by tianleh** [comment]
> I am against skipping these tests and would rather we fix them or expose them. We can test the memory setup tomorrow after my dashboards integTest run complete. Still monitoring jenkins.
> 
> Thanks.

Let me close this PR instead of merging. Thanks all for the input!

**Pull request closed without merging**
