### PR TITLE
feat: remove useless vanilla test

### LINKED ISSUE #961: [BUG]Flaky tests are found in `core-opensearch-dashboards/vanilla-opensearch-dashboards`
### What is the bug?
Flaky tests are found in `core-opensearch-dashboards/vanilla-opensearch-dashboards`, you can find the detail logs in https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/6976620693/job/18985307702?pr=960

### How can one reproduce the bug?
Create a PR against main and you will find Snapshot based E2E Cypress tests workflow / Run Cypress E2E tests action fails.

### What is the expected behavior?
The test case should pass.

### What is your host/environment?
Ubuntu latest, github CI environment

### Do you have any screenshots?
image

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description
`cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/dashboard_filtering_spec.js` test is not needed and it is never run on OSS release process. As it is flaky and keeps failing normal PR workflow actions, we decide to remove this spec.

More context: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/961#issuecomment-1828508730

### Issues Resolved

#961 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kavilla** [comment]
will look at this. thanks!

**Comment by SuZhou-Joe** [comment]
Hi @kavilla @tianleh @seraphjiang , we are running a campaign to reduce flaky test in FTRepo. Do you think it's safe that we skip the vanilla test?

**Review by kavilla — APPROVED** [review]
From my POV, these don't get executing in our CI or release testing.

**Comment by tianleh** [comment]
nonblocking: please remove the reference here as well $ yarn cypress:run-without-security --spec "cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/*.js"

**Review by tianleh — APPROVED** [review]

**Review by wanglam — APPROVED** [review]

**Review by raintygao — APPROVED** [review]

**Pull request merged**
