### PR TITLE
Fixes the span item to reflect correct text

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description

`Create user account` text doesn't exist on internal-users page. Replaced it with correct text `Create internal user`

### Issues Resolved

- Unblocks: https://github.com/opensearch-project/security-dashboards-plugin/pull/1941

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
Cypress tests are failing due to stale docker image.
@derek-ho has a PR out to fix this: https://github.com/opensearch-project/opensearch-build/pull/4468

@peterzhuamazon @gaiksaya Can we get @derek-ho's PR prioritized and merged to unblock security-dashboards-plugin CI?

**Review by derek-ho — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@tianleh @kavilla @ohltyler @CCongWang Could I get some reviews on this PR? This PR will unblock a PR in security. Thanks in advance!

**Comment by derek-ho** [comment]
We should also backport this to 2.x

**Review by CCongWang — APPROVED** [review]

**Review by yujin-emma — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
> We should also backport this to 2.x

No need. Changes are already present in 2.x

**Pull request merged**
