### PR TITLE
Update api path in main after service account removal

### PR DESCRIPTION
**Pull request by derek-ho**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
Checks will fail until: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1444#:~:text=Remove%20service%20accounts%20from%20Main%20opensearch%2Dproject/security%2Ddashboards%2Dplugin%232041 is merged

**Comment by cwperks** [comment]
Approved.

**Comment by cwperks** [comment]
> Checks will fail until: https://github.com/opensearch-project/security-dashboards-plugin/pull/2041 is merged

I just re-ran the check since associated PR has merged.

**Comment by wanglam** [comment]
Hi @derek-ho , the security release tests workflow still failed after re-run. Is that related to this PR? Just find the `plugins/security/internalusers_spec.js` was passed in [this job](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/9993757453/job/27728981708). Can we merge it to the main branch? Do we need  backport to 2.x branch?

**Comment by derek-ho** [comment]
Checking on the other failures now

**Review by cwperks — APPROVED** [review]

**Comment by cwperks** [comment]
All checks passed. Merging.

**Comment by cwperks** [comment]
@derek-ho Can you please update the description and link to the companion security-dashboards-plugin PR?

**Pull request merged**
