### PR TITLE
[Do_NOT_MERGE] run all test under new security plugin

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by derek-ho** [comment]
One issue is: https://github.com/opensearch-project/security-dashboards-plugin/pull/1705

**Comment by derek-ho** [comment]
Other issue is that security dashboards plugin seems not to be installed, checking manifests

**Comment by derek-ho** [comment]
@prudhvigodithi @rishabh6788 @peterzhuamazon seems like the latest 3.0.0 build doesn't have security dashboards plugin, but I see it present in the manifest file: https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-dashboards-3.0.0.yml, is it just because we haven't had a successful build for a while? Any way to get this plugin in the build image somehow?

```
2023-12-22T10:04:52.6475682Z {"type":"log","@timestamp":"2023-12-22T10:04:52Z","tags":["fatal","root"],"pid":2115,"message":"InvalidConfigurationError: Unknown configuration key(s): \"opensearch_security.multitenancy.enabled\", \"opensearch_security.multitenancy.tenants.preferred\", \"opensearch_security.readonly_mode.roles\", \"opensearch_security.cookie.secure\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/legacy/config/ensure_valid_configuration.js:50:11)\n    at Server.setup (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/server.js:156:5)\n    at Root.setup (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/root/index.js:60:14)\n    at bootstrap (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/bootstrap.js:113:5)\n    at Command.<anonymous> (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/cli/serve/serve.js:191:5) {\n  code: 'InvalidConfig',\n  processExitCode: 64,\n  cause: undefined\n}"}
```

Run wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz

**Comment by prudhvigodithi** [comment]
Hey @derek-ho even though its part of the manifest the security dashboards plugin failed to build for 3.0.0 version, please check the created AUTOCUT issue.
https://github.com/opensearch-project/security-dashboards-plugin/issues/1682

**Pull request closed without merging**
