### PR TITLE
[maps-dashboards] Update data source name and rebase code in maps

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
This PR does:
1. Update "data source" name from https://github.com/opensearch-project/dashboards-maps/pull/588
2. Rebase code change from 2.x to main.

### Test

Local test:
```


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/custom-import-map-dashboard      00:51        1        1        -        -        - │
  │    s/1_import_vector_map_tab.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:54        1        1        -        -        - │
  │    s/2_opensearchMapLayer.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:34        1        1        -        -        - │
  │    s/3_add_saved_object.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      02:55        2        2        -        -        - │
  │    s/4_documentsLayer.spec.js                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        07:16        5        5        -        -        -  

```

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seraphjiang — APPROVED** [review]

**Comment by junqiu-lei** [comment]
All in all, the test passed in my local and looks like failure is due to outdated maps plugin used in the CI.

Looked into the CI failure, looks like the maps UI in cypress CI isn't latest from maps-dashboards main branch. The OSD artifact used in CI come from https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7499/pipeline/164, I saw build error message for maps-dashboards and have auto cut issue: https://github.com/opensearch-project/dashboards-maps/issues/596

```
+ gh issue list --repo https://github.com/opensearch-project/dashboards-maps.git -S '[AUTOCUT] Distribution Build Failed for customImportMapDashboards-3.0.0 in:title' --label autocut,v3.0.0 --json number --jq '.[0].number'
```

cc: @vibrantvarun

**Review by SuZhou-Joe — APPROVED** [review]
Would be nice to post your local test result in the PR.

LGTM and approved, let's wait for a up-to-date build candidate to make the flow pass before merging the code.

BTW, any backport label needed? Is it for 2.13?

**Review by raintygao — APPROVED** [review]

**Comment by junqiu-lei** [comment]
> Would be nice to post your local test result in the PR.
> 
> LGTM and approved, let's wait for a up-to-date build candidate to make the flow pass before merging the code.
> 
> BTW, any backport label needed? Is it for 2.13?

Yes please help add tag `backport 2.x` and it's needed for 2.13.

**Comment by Hailong-am** [comment]
@junqiu-lei would you mind do manual backport to 2.x?

**Pull request merged**
