### PR TITLE
Update reports test

### PR DESCRIPTION
**Pull request by rupal-bq**
Signed-off-by: Rupal Mahajan <maharup@amazon.com>

### Description

- Added fix for flaky test.
- Increased timeout

### Issues Resolved

https://github.com/opensearch-project/dashboards-reporting/issues/23

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rupal-bq** [comment]
Run Opensearch-Dashboards server step failed in CI.
```
curl: (7) Failed to connect to localhost port 5601 after 1 ms: Connection refused
```

**Review by ps48 — APPROVED** [review]

**Review by anirudha — APPROVED** [review]

**Review by yujin-emma — APPROVED** [review]
Changes look good to me

**Comment by tianleh** [comment]
> Run Opensearch-Dashboards server step failed in CI.
> 
> ```
> curl: (7) Failed to connect to localhost port 5601 after 1 ms: Connection refused
> ```

It failed due to `latest` bundle OSD 3.0.0 is not ready https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4121567848/jobs/7117382797

Could you please upload your local testing result here, e.g the Cypress video?

**Comment by rupal-bq** [comment]
https://user-images.githubusercontent.com/56703525/217628016-430e704d-34d9-468d-96f1-d6df278d5e02.mp4


https://user-images.githubusercontent.com/56703525/217628096-2f6bde11-1322-4b2b-bda9-8fe50464cbf3.mp4


https://user-images.githubusercontent.com/56703525/217628156-83c85314-c7e8-4701-9d30-57f46d5f5983.mp4

https://user-images.githubusercontent.com/56703525/217628221-f17a97d6-718c-4ea3-afb1-adab4609e917.mp4

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v16.13.2 (/Users/maharup/.nvm/versions/node/v16.13.2/bin/node)                 │
  │ Specs:          4 found (plugins/reports-dashboards/01-create.spec.js, plugins/reports-dashboa │
  │                 rds/02-edit.spec.js, plugins/reports-dashboards/03-details.spec.js, plugins/re │
  │                 ports-dashboards/04-download.spec.js)                                          │
  │ Searched:       cypress/integration/plugins/reports-dashboards/*.js                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/reports-dashboards/01-create.spec.js                                    (1 of 4)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Couldn't determine Mocha version


  Cypress
    ✓ Visits Reporting homepage (128296ms)
    ✓ Visit Create page (64474ms)
    ✓ Create a new on-demand dashboard report definition (62105ms)
    ✓ Create a new on-demand visualization report definition (64168ms)
    ✓ Create a new on-demand saved search report definition (62042ms)
    ✓ Create a new dashboard daily recurring report definition (64346ms)
    ✓ Create a new visualization daily recurring report definition (62039ms)
    ✓ Create a new saved search daily recurring report definition (64052ms)
    ✓ Create a new dashboard interval recurring report definition (62106ms)
    ✓ Create a new visualization interval recurring report definition (64553ms)
    ✓ Create a new saved search interval recurring report definition (62361ms)
    ✓ Create a dashboard cron-based report definition (64590ms)
    ✓ Create a visualization cron-based report definition (62033ms)
    ✓ Create a saved search cron-based report definition (64174ms)


  14 passing (16m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        14                                                                               │
  │ Passing:      14                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     15 minutes, 51 seconds                                                           │
  │ Spec Ran:     plugins/reports-dashboards/01-create.spec.js                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
    Compression progress:  21%
    Compression progress:  41%
    Compression progress:  63%
    Compression progress:  86%
  -  Finished processing: /Users/maharup/ws_github/opensearch-dashboards-functional-t   (49 seconds)
                          est/cypress/videos/plugins/reports-dashboards/01-create.spe               
                          c.js.mp4                                                                  


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/reports-dashboards/02-edit.spec.js                                      (2 of 4)


  Cypress
    ✓ Visit edit page, update name and description (67963ms)
    ✓ Visit edit page, change report trigger (64120ms)
    ✓ Visit edit page, change report trigger back (64160ms)


  3 passing (3m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     3 minutes, 16 seconds                                                            │
  │ Spec Ran:     plugins/reports-dashboards/02-edit.spec.js                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/maharup/ws_github/opensearch-dashboards-functional-t    (9 seconds)
                          est/cypress/videos/plugins/reports-dashboards/02-edit.spec.               
                          js.mp4                                                                    


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/reports-dashboards/03-details.spec.js                                   (3 of 4)


  Cypress
    ✓ Visit report definition details page (67968ms)
    ✓ Go to edit report definition from report definition details (64531ms)
    ✓ Verify report source URL on report definition details (63969ms)
    ✓ Delete report definition from details page (64339ms)
    ✓ Visit report details page (64042ms)
    ✓ Verify report source URL on report details (63934ms)


  6 passing (6m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6                                                                                │
  │ Passing:      6                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     6 minutes, 28 seconds                                                            │
  │ Spec Ran:     plugins/reports-dashboards/03-details.spec.js                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
    Compression progress:  62%
  -  Finished processing: /Users/maharup/ws_github/opensearch-dashboards-functional-t   (19 seconds)
                          est/cypress/videos/plugins/reports-dashboards/03-details.sp               
                          ec.js.mp4                                                                 


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  plugins/reports-dashboards/04-download.spec.js                                  (4 of 4)


  Cypress
    ✓ Download from reporting homepage (67433ms)
    ✓ Download pdf from in-context menu (6387ms)
    ✓ Download png from in-context menu (7898ms)
    ✓ Download csv from saved search in-context menu (11127ms)
    ✓ Download from Report definition details page (62390ms)


  5 passing (3m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 35 seconds                                                            │
  │ Spec Ran:     plugins/reports-dashboards/04-download.spec.js                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/maharup/ws_github/opensearch-dashboards-functional-t    (8 seconds)
                          est/cypress/videos/plugins/reports-dashboards/04-download.s               
                          pec.js.mp4                                                                


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/reports-dashboards/01-creat      15:51       14       14        -        -        - │
  │    e.spec.js                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/02-edit.      03:16        3        3        -        -        - │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/03-detai      06:28        6        6        -        -        - │
  │    ls.spec.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/04-downl      02:35        5        5        -        -        - │
  │    oad.spec.js                                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        28:12       28       28        -        -        -  

✨  Done in 1809.18s.
```

**Comment by rupal-bq** [comment]
> > Run Opensearch-Dashboards server step failed in CI.
> > ```
> > curl: (7) Failed to connect to localhost port 5601 after 1 ms: Connection refused
> > ```
> 
> It failed due to `latest` bundle OSD 3.0.0 is not ready https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4121567848/jobs/7117382797
> 
> Could you please upload your local testing result here, e.g the Cypress video?

added local results

**Review by tianleh — APPROVED** [review]

**Pull request merged**
