### PR TITLE
Add functional test for ml-commons-dashboards overview page

### PR DESCRIPTION
**Pull request by wanglam**
### Description

Add functional test for ml-commons-dashboards overview page

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CCongWang** [comment]
Hi @wanglam , could you please upload local test results? looks like there is something wrong with the workflow, looking into it

**Comment by CCongWang** [comment]
Hi @ps48 @joshuali925 , looks like workflow failed because dashboards can't start: https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4201543244/jobs/7288650841
And it complains about `Error: Cannot find module 'performance-now'\nRequire stack:\n- /home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.js`, could you please take a look? Thank you!

**Comment by wanglam** [comment]
@CCongWang Sure. Here is my local test results.
image
I don't know why can't find module "performance-now", is there any steps I missed?

**Comment by CCongWang** [comment]
> @CCongWang Sure. Here is my local test results. image I don't know why can't find module "performance-now", is there any steps I missed?

Thanks for sharing! yeah I don't know either.. but definitely not related to your code change!

**Review by CCongWang — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]

**Comment by wanglam** [comment]
> Looks good. Please add backport labels if needed.

Thanks. backport 2.x label has been added.

**Pull request merged**
