### PR TITLE
Adds developer guide

### LINKED ISSUE #290: [BUG] Instructions on how to run the repo not clear
### What is the bug?
Information on how to run the tests in this repo are currently present in the [CONTRIBUTING.md](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md). This does not follow the readme structure followed by the rest of the project e.g. OpenSearch Dashboards that has this information in [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md). Additionally, the  installation instructions are a bit confusing and could use some improvement.

### How can one reproduce the bug?
No developer guide readme

### What is the expected behavior?
A separate `DEVELOPER_GUIDE.md` for installation steps, how to run tests etc. like the [Getting Started](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started) section in OpenSearch Dashboards

### PR DESCRIPTION
**Pull request by ashwin-pc**
Signed-off-by: Ashwin Pc <ashwinpc@amazon.com>

### Description

- Adds a developer guide to the repo
- fixes liniting errors

### Issues Resolved

#290 
#307 (Partial fix) Left a todo for one of the changes that that was commented out after speaking to the developer

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
Sorry for checking this PR late. But we do have a developer guide under contributing md. https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md#developer-guide which contains more detailed instructions. 

Probably you can add the instructions over there. Then I can do a bulk move over to the proper folder structure.

**Comment by ashwin-pc** [comment]
@tianleh Ah missed the testing and onboarding sections. Would you rather have me move those sections from contributing here instead? That way we dont need to duplicate the work. If you prefer to do the move yourself, i can add my sections in the contributing doc.Let me know which one is ideal.

**Comment by tianleh** [comment]
> @tianleh Ah missed the testing and onboarding sections. Would you rather have me move those sections from contributing here instead? That way we dont need to duplicate the work. If you prefer to do the move yourself, i can add my sections in the contributing doc.Let me know which one is ideal.

Let me take care of the bulk restructure. You can add your sections into the existing doc https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md#developer-guide I am in the middle of creating another PR which may address some of the linting issues. Once you sync my latest change, your PR will be much simpler.

Wish I checked this earlier to avoid the convenience. @ashwin-pc

**Comment by ashwin-pc** [comment]
No problem! I'll hold off on this for a lil then.

**Comment by tianleh** [comment]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/317 is merged. Please rebase from `main` and update PR accordingly

**Comment by tianleh** [comment]
I will sync up with @ashwin-pc about the plan to move forward.

**Comment by ashwin-pc** [comment]
closing this since its superseded by changes made in #403

**Pull request closed without merging**
