### PR TITLE
[Backport 2.x] Add functional test for datasources at observability dashboards plugin

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
Add functional test for datasources at observability dashboards plugin

### Issues Resolved
* Backport https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/987

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ruanyl** [comment]
@RyanL1997 I fixed an testing running forever issue recently, and I noticed two tests are failing for `datasources_dashboard.spec.js`: https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7712151209/job/21019043851?pr=1023

Could you take a look?

**Comment by Hailong-am** [comment]
> I fixed an testing running forever issue recently for observability,

@ruanyl can you check https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7720266678/job/21044878653?pr=1024, it still run forever?

**Comment by ruanyl** [comment]
> > I fixed an testing running forever issue recently for observability,
> 
> @ruanyl can you check https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7720266678/job/21044878653?pr=1024, it still run forever?

The PR hasn't merged https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1023

**Comment by RyanL1997** [comment]
@ruanyl I can take a look on this. This is due to the enable of security, so that the url has the slug of security tenant.

**Comment by RyanL1997** [comment]
Hi @ruanyl, thx for the reminder. I have fixed the issue. Could you please verify that?

**Review by ruanyl — APPROVED** [review]

**Comment by ruanyl** [comment]
@RyanL1997 thanks for the fix! Btw, maybe you want to create another PR to apply the same fix to `main` :)

**Review by Hailong-am — APPROVED** [review]

**Pull request merged**
