### PR TITLE
Temporarily remove reporting menu tests in notebooks

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description

see https://github.com/opensearch-project/dashboards-observability/pull/202

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamsi-amazon — APPROVED** [review]

**Review by rupal-bq — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
1. Please confirm whether the error is expected. https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3916132215/jobs/6694969823
2. If backport is needed, please add such labels. 

@joshuali925 Feel free to merge

**Comment by tianleh** [comment]
@joshuali925 Do you want to merge the PR at this time?

**Comment by tianleh** [comment]
Also please add any backport labels if needed. Thanks

**Comment by joshuali925** [comment]
sorry forgot about this PR. I'm waiting for https://github.com/opensearch-project/dashboards-observability/pull/229 to be merged, this will revert the reporting menu changes, then I'll update tests if needed in a new PR. 

not sure why removing tests can introduce error in CI. Will check in new PR later.

**Pull request closed without merging**
