### PR TITLE
Adds additional VisBuilder tests and commands

### PR DESCRIPTION
**Pull request by ashwin-pc**
Signed-off-by: Ashwin Pc <ashwinpc@amazon.com>

### Description

Visbuilder Tests
- Updates Basic test
- Adds Dashboard test for visbuilder visualizations
- Adds Experimental test for visbuilder
- Adds Basic tests for each visualization type

Visbuilder misc
- Adds additional data and saved objects for Visbuilder tests
- Adds Edit agg visbuilder command
- Updates common commands and consolidates variables

General
- Adds `importSavedObjects` command
- Adds `deleteSavedObject` command
- Adds `deleteSavedObjectByType` command
- Adds `setAdvancedSetting` command

### Test Videos

Basic test (Updated)

https://user-images.githubusercontent.com/20453492/196831881-1b463881-3848-43f2-885e-262e22f79aa2.mp4

Dashboard test

https://user-images.githubusercontent.com/20453492/196831889-165fceea-73d9-4d1b-a703-b0e8356803b9.mp4

Experimental test

https://user-images.githubusercontent.com/20453492/196831896-430e6aff-5c62-4701-9806-0030bb0d21d3.mp4

Vis Types:

Metric:

https://user-images.githubusercontent.com/20453492/196835613-992d91df-d5fc-4387-b68d-3635441ee287.mp4

Bar Chart:

https://user-images.githubusercontent.com/20453492/196835656-a52cb3b1-7ed5-47b6-94ce-4b4594fce0ef.mp4

Line Chart:

https://user-images.githubusercontent.com/20453492/196835662-e6fa33fa-06f5-46b4-baf3-e9b14cfde70d.mp4

Area Chart:

https://user-images.githubusercontent.com/20453492/196835668-c2e3f907-c7c6-42c8-93c5-3abc19459403.mp4

Note: Depends on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2610 being merged and built

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashwin-pc** [comment]
The two failing tests have corresponding fixes in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2610 which has been merged. @tianleh how long before we can rerun these tests so that those changes are picked up?

**Comment by tianleh** [comment]
> The two failing tests have corresponding fixes in [opensearch-project/OpenSearch-Dashboards#2610](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2610) which has been merged. @tianleh how long before we can rerun these tests so that those changes are picked up?

Just see a new successful build.

```

BUILD_NUMBER=[4175]
MESSAGE=Successful Build
BUILD_URL: https://build.ci.opensearch.org/job/distribution-build-opensearch-dashboards/4175/
MANIFEST: 3.0.0/opensearch-dashboards-3.0.0.yml
```

let me rerun the workflow.

**Comment by tianleh** [comment]
The new run still has a failed test https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3285900713/jobs/5429768670 Could you take a look? @ashwin-pc  

The build links shows that "[Vis Builder] Update vislib params and misc fixes (#2610)" was included in the build.

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
Please add the backport label if needed.

**Review by seraphjiang — APPROVED** [review]

**Comment by seraphjiang** [comment]
> Please add the backport label if needed.

@tianleh @CCongWang 

One observation, not every contributor has permission to add label. In such case, maintainer should take responsibility to triage and add label

**Comment by ashwin-pc** [comment]
@tianleh Looks like the automated backport failed. Will you be creating a manual backport for this?

**Comment by tianleh** [comment]
> @tianleh Looks like the automated backport failed. Will you be creating a manual backport for this?

After merging another backporting change and re-triggering the backporting workflow by removing and adding the label, the backport is now automatically created https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/350 @ashwin-pc

**Pull request merged**
