### PR TITLE
Fix flaky test for vis-augmenter

### LINKED ISSUE #1118: [BUG] Flaky test of vis-augmenter
### What is the bug?
vis-augmenter test cases are failed when security is enabled, that because index pattern been created into `.kibana` index that's for global tenant. When run tests, the default tenant is private, that leads create dashboards page don't load correctly as index pattern is missing.

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7998888456/job/21845807125

https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/113890546/1044dfb1-2090-4b5b-be01-1f01a0ad40eb

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description

Add some wait time to dashboard to be searchable

### Issues Resolved

#1118 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ruanyl — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by Hailong-am** [comment]
pls hold on merge, there is no test run for this change.

**Comment by xluo-aws** [comment]
Saw there are failed test cases related to visualization, is it supposed to be fixed by this change or it's not related?

**Comment by Hailong-am** [comment]
> Saw there are failed test cases related to visualization, is it supposed to be fixed by this change or it's not related?

It's not related, this PR focus on vis-augmenter related test cases.

**Comment by ruanyl** [comment]
@Hailong-am what's the status of this PR? can we merge?

**Comment by Hailong-am** [comment]
> @Hailong-am what's the status of this PR? can we merge?

Still have issue for the vis-augmenter, under investigation

**Comment by Hailong-am** [comment]
test result https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7999641394

without security 
```
 Running:  core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/          (35 of 41)
            dashboard_spec.js                                                                       


  Vis augmenter - existing dashboards work as expected
    dashboard with ineligible, eligible, and vega visualizations
      ✓ View events option does not exist for any visualization (90866ms)
      ✓ Validate non-vega visualizations are not rendered with vega under the hood (9762ms)


  2 passing (2m)     
```

with security
```
                                                                                                  
  Running:  core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/          (35 of 41)
            dashboard_spec.js                                                                       
  Vis augmenter - existing dashboards work as expected
    dashboard with ineligible, eligible, and vega visualizations
      ✓ View events option does not exist for any visualization (91996ms)
      ✓ Validate non-vega visualizations are not rendered with vega under the hood (9924ms)
  2 passing (2m)
```

**Review by kavilla — APPROVED** [review]

**Pull request merged**
