### PR TITLE
Update tenant to global to maps-dashboards

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description

Update tenant to global to maps-dashboards

### Test
```
arm64-tar-with-security:

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/custom-import-map-dashboard      00:30        1        1        -        -        - │
  │    s/1_import_vector_map_tab.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:49        1        1        -        -        - │
  │    s/2_opensearchMapLayer.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:42        1        1        -        -        - │
  │    s/3_add_saved_object.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      02:13        2        2        -        -        - │
  │    s/4_documentsLayer.spec.js                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        06:15        5        5        -        -        -  

Done in 470.67s.

x64-tar-with-security:

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/custom-import-map-dashboard      00:27        1        1        -        -        - │
  │    s/1_import_vector_map_tab.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:43        1        1        -        -        - │
  │    s/2_opensearchMapLayer.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      01:41        1        1        -        -        - │
  │    s/3_add_saved_object.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/custom-import-map-dashboard      02:24        2        2        -        -        - │
  │    s/4_documentsLayer.spec.js                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        06:17        5        5        -        -        -  
```

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kavilla** [comment]
is to circumvent long round trip times of http calls on startup when adding security plugin

**Comment by junqiu-lei** [comment]
> is to circumvent long round trip times of http calls on startup when adding security plugin

@kavilla Yes, the flaky only happened when security enabled.

**Review by peterzhuamazon — APPROVED** [review]

**Review by ruanyl — APPROVED** [review]

**Comment by ruanyl** [comment]
@junqiu-lei the auto backport failed, could you please do a manual backport?

**Comment by junqiu-lei** [comment]
@ruanyl this PR targeted to 2.x branch to fix the issue firstly. Once the release 2.12 integ test stable in Jenkins CI, will merge related changes to main.

**Pull request merged**
