### PR TITLE
Integration tests for broken safari link

### PR DESCRIPTION
**Pull request by leanneeliatra**
### Description
Tests that when the link is copyed in Safari, it is copyed successfully and can be visited.
When visiting `Discover` >` Copy link`

### Issues Resolved
Integration tests for the associated bugfix:
[[BUG] Share > Copy link broken in Safari #1716](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1716)

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ruanyl** [comment]
Hi @leanneeliatra, could you convert this PR to "draft" if it is "IN PROGRESS"?

**Comment by leanneeliatra** [comment]
This PR was closed accidentally, it is now reopened.

**Comment by leanneeliatra** [comment]
Tests are passing locally

**Comment by leanneeliatra** [comment]
To note, this issue was only occuring in safari, is there anything that needs to be considered for the CI once this is merged or is it sufficient that the test runs as per the other tests, in --headless mode? Thanks

For testing locally I am testing this in safari using: https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental (WebKit is available only via an experimental feature of Cypress). Given that this is experimental, it cannot be merged into the CI pipeline.

**Comment by leanneeliatra** [comment]
Cypress tests passing locally
Screenshot 2023-11-13 at 20 40 33

Screenshot 2023-11-13 at 20 40 41

**Comment by leanneeliatra** [comment]
This can now be reviewed please, the cypress workflow check doesn't seem to be passing but as you can see above they are so I am a bit confused there, can anyone direct please?
@Hailong-am @xluo-aws @SuZhou-Joe @ruanyl

**Comment by SuZhou-Joe** [comment]
> **This can now be reviewed please** The cypress workflow check `Snapshot based E2E Cypress tests workflow / Run Cypress E2E tests (pull_request)` doesn't seem to be passing but as you can see above they are, so I am a bit confused there, can anyone direct please? @Hailong-am @xluo-aws @SuZhou-Joe @ruanyl

For the snapshot based test, it should has something to do with the Node version upgrade to v18 and you can ignore that for now.

But I am a little bit confused why the flow `Security Release tests workflow in Bundled OpenSearch Dashboards` was unable to run as there is some changes matching its filter configuration, set up a [issue](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/951) to check that

**Comment by leanneeliatra** [comment]
> > Thank you @SuZhou-Joe for the feedback, much appreciated.
1. Yes the file location suggested seems like a better place for the new test, I have added it to that location and changed the name to be more descriptive.
`cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_share_copy_link_test.js`
2. It would be great to get guidance on this. I have tested in Safari and the copy link works as expected but further guidance on whether we need to do something with the test for merging into the CI would be great.
3. Thanks for opening the ticket with regard to `Security Release tests workflow in Bundled OpenSearch Dashboards`

**Comment by leanneeliatra** [comment]
> This can now be reviewed please if anyone has a moment. Thanks.
cc @Hailong-am @xluo-aws @ruanyl

**Review by SuZhou-Joe — APPROVED** [review]

**Review by Hailong-am — APPROVED** [review]

**Comment by Hailong-am** [comment]
waiting for https://github.com/opensearch-project/security-dashboards-plugin/pull/1633 be merged

**Comment by leanneeliatra** [comment]
These can now be merged @Hailong-am, thank you for your assistance.

**Pull request merged**
