### PR TITLE
[Feature Anywhere / Vis Augmenter] Add test flows for integration with AD plugin

### LINKED ISSUE #426: [Feature Anywhere] Add tests to create `augment-vis` saved objects for AD
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

Add flows from a Dashboard to link a detector to a visualization, and confirm the saved object is created as expected.

### LINKED ISSUE #428: [Feature Anywhere] Add tests for detector auto-creation from a visualization
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

Add a test flow where a detector config is auto-generated and created from a visualization, and that the saved object is created as expected.

### LINKED ISSUE #431: [Feature Anywhere] Add tests to show eligibility of the feature or not
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

The feature to augment a vis should only be visible when a vis is eligible (of type `line` and meeting other config requirements). Add tests to confirm the plugin options show or not based on eligibility.

### LINKED ISSUE #432: [Feature Anywhere] Add tests for new 'View events' flyout
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

New flyout should handle multiple scenarios and ensure it is rendered correctly:
- no events
- events for one plugin
- events for multiple plugins
- reaching plugin resource limit (if exists) and making scrollable or searchable, or showing most relevant plugin resources (?)

Last bullet point is an open question for now - will update once that decision has been finalized

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

Add test flows for integration with AD plugin
- Adding / removing associations of detectors to a vis
- Auto-creation flow of detectors from a vis
- Eligibility of a vis
- `augment-vis` saved objects - checking the generation and automatic cleanup of them
- View events flyout with associated anomaly detectors

Also refactors the create sample detector flow into a helper fn so it can be used multiple places

### Issues Resolved

Closes #426 
Closes #428 
Closes #431 
Closes #432 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
Will be adding more tests related to the created saved objects before taking out of draft.

**Comment by SuZhou-Joe** [comment]
@ohltyler Can we make this all the workflows pass? If not, please post with the test result in your local env.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> @ohltyler Can we make this all the workflows pass? If not, please post with the test result in your local env.

Also notice the linting is having errors, reset approval for now, thanks.

**Comment by ohltyler** [comment]
@peterzhuamazon fixed linting issue.

@SuZhou-Joe workflow failures I'm seeing are unrelated and due to 3.0 unavailability. Local is passing. Worth noting that this is going to a feature branch, and before merging into `main`/`2.x`, will update or create new workflows for testing the feature (the core `vis_augmenter` test suite + the ones added in this PR).
```
  Anomaly detection integration with vis augmenter
    ✓ Shows empty state when no associated detectors (42516ms)
    ✓ Create new detector from visualization (58109ms)
    ✓ Associate existing detector - creation flow (58235ms)
    ✓ Associate existing detector - associated detectors flow (53582ms)
    ✓ Deleting linked detector shows error once and removes from associated detectors list (76820ms)


  5 passing (5m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 minutes, 52 seconds                                                            │
  │ Spec Ran:     plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spe │
  │               c.js                                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
    Compression progress:  87%
  -  Finished processing: /Users/ohltyler/workspace/opensearch/feature-anywhere/legac   (15 seconds)
                          y-test/opensearch-dashboards-functional-test/cypress/videos
                          /plugins/anomaly-detection-dashboards-plugin/vis_augmenter/
                          associate_detector_spec.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vi            (2 of 3)
            s_saved_object_spec.js


  AD augment-vis saved objects
    ✓ Associating a detector creates a visible saved object (74593ms)
    ✓ Created AD saved object has correct fields (9111ms)
    ✓ Removing an association deletes the saved object (27517ms)
    ✓ Deleting the visualization from the edit view deletes the saved object (15659ms)


  4 passing (2m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 9 seconds                                                             │
  │ Spec Ran:     plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_obje │
  │               ct_spec.js                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/ohltyler/workspace/opensearch/feature-anywhere/legac    (7 seconds)
                          y-test/opensearch-dashboards-functional-test/cypress/videos
                          /plugins/anomaly-detection-dashboards-plugin/vis_augmenter/
                          augment_vis_saved_object_spec.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anoma            (3 of 3)
            ly_events_spec.js


  View anomaly events in flyout
    ✓ Action does not exist if there are no VisLayers for a visualization (31768ms)
    ✓ Action does exist if there are VisLayers for a visualization (45814ms)
    ✓ Basic components show up in flyout (15257ms)
    ✓ Removing all VisLayers hides the view events action again (29123ms)


  4 passing (2m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 5 seconds                                                             │
  │ Spec Ran:     plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_sp │
  │               ec.js                                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/ohltyler/workspace/opensearch/feature-anywhere/legac    (6 seconds)
                          y-test/opensearch-dashboards-functional-test/cypress/videos
                          /plugins/anomaly-detection-dashboards-plugin/vis_augmenter/
                          view_anomaly_events_spec.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/anomaly-detection-dashboard      04:52        5        5        -        -        - │
  │    s-plugin/vis_augmenter/associate_de                                                         │
  │    tector_spec.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      02:09        4        4        -        -        - │
  │    s-plugin/vis_augmenter/augment_vis_                                                         │
  │    saved_object_spec.js                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      02:05        4        4        -        -        - │
  │    s-plugin/vis_augmenter/view_anomaly                                                         │
  │    _events_spec.js                                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        09:07       13       13        -        -        -
```

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by SuZhou-Joe** [comment]
@ohltyler Need to backport 2.x?

**Comment by ohltyler** [comment]
> @ohltyler Need to backport 2.x?

just putting everything into feature branch. then will merge entire thing to main + 2.x

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
