### PR TITLE
Update gantt chart tenant

### PR DESCRIPTION
**Pull request by ps48**
### Description

Adds global tenant to gantt-charts 

### Issues Resolved

https://github.com/opensearch-project/dashboards-visualizations/issues/357
https://github.com/opensearch-project/dashboards-visualizations/issues/362

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]
do other plugins need this?

**Comment by ps48** [comment]
> do other plugins need this?

Not sure, but some plugins already have this. Gantt-charts needs this cause it's using saved-objects and index-patterns.

**Comment by ps48** [comment]
Hi @SuZhou-Joe @ruanyl, Can you please review this PR and help backport it to main branch?

**Comment by SuZhou-Joe** [comment]
@ps48 Actually the standard flow should be that
1. raise the PR in main branch.
2. backport to 2.x and merge.

Please try to follow the best practice next time. :D

**Review by SuZhou-Joe — APPROVED** [review]

**Pull request merged**
