### PR TITLE
Remove unnecessary app analytics tests

### LINKED ISSUE #289: Remove Observability flaky tests from FTR
### Is your feature request related to a problem?
Some of the tests/test suits for Observability plugin are flaky which causes false alarms for releases from time to time.

### What solution would you like?
Remove unnecessary but prone-to-be-flaky tests, and fix/improve those that are necessary.

### PR DESCRIPTION
**Pull request by eugenesk24**
Signed-off-by: Eugene Lee <eugenesk@amazon.com>

### Description

Remove App Analytics tests that are not necessary. This is to reduce flakiness. 

### Issues Resolved
#289 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
Rerun https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3237324644 to see if it will succeed.

**Comment by tianleh** [comment]
Any backport is needed? @eugenesk24

**Comment by tianleh** [comment]
@eugenesk24 looks like the tests are failing https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3237324644/jobs/5392223936 

Also if backport is needed, please add the corresponding backport label.

**Comment by tianleh** [comment]
@joshuali925 Do you know if this PR is still needed? Could we close if no active development is on it?

**Comment by joshuali925** [comment]
not sure if it's still relevant, @mengweieric?

**Comment by tianleh** [comment]
> not sure if it's still relevant, @mengweieric?

@mengweieric Can you confirm? If no longer needed, we can close the PR since it has been sitting in the queue for a while.

**Pull request closed without merging**
