### PR TITLE
[Vis Augmenter / Feature Anywhere] Add tests in core OSD and AD plugin

### LINKED ISSUE #426: [Feature Anywhere] Add tests to create `augment-vis` saved objects for AD
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

Add flows from a Dashboard to link a detector to a visualization, and confirm the saved object is created as expected.

### LINKED ISSUE #428: [Feature Anywhere] Add tests for detector auto-creation from a visualization
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

Add a test flow where a detector config is auto-generated and created from a visualization, and that the saved object is created as expected.

### LINKED ISSUE #431: [Feature Anywhere] Add tests to show eligibility of the feature or not
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

The feature to augment a vis should only be visible when a vis is eligible (of type `line` and meeting other config requirements). Add tests to confirm the plugin options show or not based on eligibility.

### LINKED ISSUE #432: [Feature Anywhere] Add tests for new 'View events' flyout
Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2880

New flyout should handle multiple scenarios and ensure it is rendered correctly:
- no events
- events for one plugin
- events for multiple plugins
- reaching plugin resource limit (if exists) and making scrollable or searchable, or showing most relevant plugin resources (?)

Last bullet point is an open question for now - will update once that decision has been finalized

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

Adds tests for the Vis Augmenter / Feature Anywhere feature. Includes new tests in core OSD + tests in AD plugin to test the integration of the plugin with the feature. Includes many helper fns in core OSD for plugins to use too bootstrap a test cluster with appropriate data to test plugin integration (e.g., create a dashboard with a feature-eligible visualization and sufficient sample data).

NOTE: there may be follow-ups to refactor when these new test suites are run, and some existing script cmds may need to be updated.

### Issues Resolved

Closes #426 
Closes #428 
Closes #431 
Closes #432 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ananzh** [comment]
@ohltyler is this for 2.9?

**Comment by SuZhou-Joe** [comment]
I am not very sure if it has any different between the last [PR](#727)

**Comment by ohltyler** [comment]
> I am not very sure if it has any different between the last [PR](#727).

The previous PR (+ other ones) were merged to the feature branch. This PR is merging the feature branch into main.

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by SuZhou-Joe** [comment]
@ohltyler Thanks, but I mean that if there is difference, perhaps we need to post the test result of your local env as the workflow failed.

**Review by kavilla — APPROVED** [review]

**Comment by kavilla** [comment]
@ohltyler had to revert this PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/748

Issue: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/749

**Pull request merged**
