### PR TITLE
Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains.

### PR DESCRIPTION
**Pull request by AWSHurneyt**
### Description
Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains.

### Issues Resolved
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/867

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by AWSHurneyt** [comment]
I don't have permissions to add labels. Could someone add the `backport 2.x`, and `backport 2.12` labels?

**Comment by AWSHurneyt** [comment]
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/alerting-dashboards-plugin/      03:59        3        3        -        -        - │
  │    acknowledge_alerts_modal_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      05:10        5        5        -        -        - │
  │    alert_spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      03:31        2        2        -        -        - │
  │    alerts_dashboard_flyout_spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      10:47        4        4        -        -        - │
  │    bucket_level_monitor_spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      07:31        6        6        -        -        - │
  │    cluster_metrics_monitor_spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      03:04        2        2        -        -        - │
  │    composite_level_monitor_spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      10:57        5        5        -        -        - │
  │    document_level_monitor_spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      01:22        1        1        -        -        - │
  │    monitors_dashboard_spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      17:00        8        8        -        -        - │
  │    query_level_monitor_spec.js                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by SuZhou-Joe** [comment]
LGTM and approved, but could you please elaborate more on why need to increase the timeout to 60000?

**Comment by AWSHurneyt** [comment]
> LGTM and approved, but could you please elaborate more on why need to increase the timeout to 60000?

60000 is mostly arbitrary; but I did notice that it would sometimes take a very long time (more than 30 seconds) for pages to refresh during the cypress tests. That was causing tests to fail.

**Review by xluo-aws — APPROVED** [review]

**Comment by Hailong-am** [comment]
@AWSHurneyt both backport 2.x and 2.12 are failed, you might need do manual backport.

**Pull request merged**
