### PR TITLE
[Vis Builder] Updates tests to visBuilder key

### PR DESCRIPTION
**Pull request by ashwin-pc**
Signed-off-by: Ashwin Pc <ashwinpc@amazon.com>

### Description

The existing VisBuilder tests use the `wizard` key that has now been updated to `visBuilder`. This Pr updates the keys and the tests associated.

<details><summary>Screen recordings</summary>

https://user-images.githubusercontent.com/20453492/199457058-330d997d-f5a5-4db8-96c0-c54d61a16fd4.mp4

https://user-images.githubusercontent.com/20453492/199457295-eb3545d0-a196-4c6b-8c96-f0d0938b62c0.mp4

https://user-images.githubusercontent.com/20453492/199457310-d054d1ea-488a-4103-80c0-18921245f56e.mp4

#### Vis Types

https://user-images.githubusercontent.com/20453492/199457372-a8f0fa99-db14-4db3-9754-e382cd61ed1f.mp4

https://user-images.githubusercontent.com/20453492/199457384-6a872e5b-49c3-4b03-b15c-6bb99166bfdf.mp4

https://user-images.githubusercontent.com/20453492/199457394-6e48c43d-dba2-45f1-8aa8-189b0e357c1d.mp4

https://user-images.githubusercontent.com/20453492/199457406-1ec234a0-9978-4694-9506-0053bcaa2bc1.mp4

</details>

### Issues Resolved

related to https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1706

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kavilla — APPROVED** [review]

**Review by bandinib-amzn — APPROVED** [review]

**Comment by ashwin-pc** [comment]
The OSD build seems to be failing due to other issues. Can we merge this in given the screenshots attached and I can fix any followup issues in a followup PR

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
Currently it has label for 2.x backport. Does it need 2.4 backport as well since we already have 2.4 branch?

**Comment by tianleh** [comment]
> The OSD build seems to be failing due to other issues. Can we merge this in given the screenshots attached and I can fix any followup issues in a followup PR

Sure

**Comment by ashwin-pc** [comment]
> Currently it has label for 2.x backport. Does it need 2.4 backport as well since we already have 2.4 branch?

Yes it does! thank you!

**Comment by AMoo-Miki** [comment]
I will manually take it to 2.x and try to backport to 2.4 from there.

**Pull request merged**
