### PR TITLE
feat: add function test for IM plugin

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
Signed-off-by: suzhou <suzhou@amazon.com>

### Description

[Describe what this change achieves]

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CCongWang** [comment]
Hi @SuZhou-Joe , have you merged your functionality code change into main branch? looks like the artifact from main branch doesn't have your change, in this case, it's expected that workflow will fail.
We propose that:
1. We first merge your test PR into 2.x branch since your code change is in 2.5, if you rebase, the workflow should be triggered on your 2.x PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/442; once the workflow is passed, we merge it and backport to 2.5.
2. Could you also merge your functionality code change into main branch? Then the workflow on this PR should pass, we merge this PR to main.
Let you know if it makes sense or if you have any questions!

**Comment by SuZhou-Joe** [comment]
> 2\. workflow



> Hi @SuZhou-Joe , have you merged your functionality code change into main branch? looks like the artifact from main branch doesn't have your change, in this case, it's expected that workflow will fail. We propose that:
> 
> 1. We first merge your test PR into 2.x branch since your code change is in 2.5, if you rebase, the workflow should be triggered on your 2.x PR: [feat: add function test for IM plugin on v2.5 #442](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/442); once the workflow is passed, we merge it and backport to 2.5. If the workflow fails for some reason, we can discuss then, and it will be helpful if you add local test results.
> 2. Could you also merge your functionality code change into main branch? Then the workflow on this PR should pass, we merge this PR to main.
> 
> Let you know if it makes sense or if you have any questions!

Hi @CCongWang.
1. the PR to 2.x won't do any checks.
image
So I think the first way can not work.

2. I've already merged my IM plugin's code into main but the OSD bundle on v3.0 is very old and does not include the changes on v2.5.

image

**Comment by SuZhou-Joe** [comment]
Hi, @peterzhuamazon . Below are the result for this E2E test in our plugin repo.

1. on 2.x/2.5: https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/3888858984
2. on main: TBD

**Comment by SuZhou-Joe** [comment]
The cypress test run result:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4169753897/jobs/7218052925

All specs passed in 2.5 version.

**Review by CCongWang — APPROVED** [review]

**Review by tianleh — APPROVED** [review]

**Pull request merged**
