### PR TITLE
add ashwin-pc to maintainers

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description

The maintainers have voted https://github.com/ashwin-pc as maintainer. Also @ashwin-pc  agreed to join as maintainer.

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seraphjiang — APPROVED** [review]

**Comment by seraphjiang** [comment]
Thanks and Congrats @ashwin-pc

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Hi @tianleh I am good with this change but we also need to add @ashwin-pc to the codeowner or he cannot approve PRs.

https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/CODEOWNERS

Thanks.

**Comment by tianleh** [comment]
> Hi @tianleh I am good with this change but we also need to add @ashwin-pc to the codeowner or he cannot approve PRs.
> 
> https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/CODEOWNERS
> 
> Thanks.

Currently the repo requires 2 approvals with write permission for PR review. Team is not used during the process. My plan is to grant @ashwin-pc maintainer permission after the PR merge. Let me know if this works. @peterzhuamazon

**Review by peterzhuamazon — APPROVED** [review]

**Comment by tianleh** [comment]
@peterzhuamazon Also, is it general practice to update maintainers in all `.x` branches?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Also, is it general practice to update maintainers in all `.x` branches?

I am not sure about that tho.

**Comment by tianleh** [comment]
> I am not sure about that tho.

I will ignore the backport and let's refer to the `main` branch for maintainers.

**Pull request merged**
