### PR TITLE
Fix reports dashboards test

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description

Fix Download csv from saved search in-context menu test

### Issues Resolved

N/A

### Check List

- [ x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rupal-bq** [comment]
Will also need to forward-port to 2.x and main

**Comment by rupal-bq** [comment]
Can we try rerunning https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7926565337/job/21641516636?pr=1089? Tests are working locally. Snapshot might not be updated when I raised PR.

**Comment by rupal-bq** [comment]
CI is failing because [latest changes](https://github.com/opensearch-project/dashboards-reporting/pull/296) aren't taken by [build](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/14400ed76ca9a064bb75090ce2292b2688a37a05/.github/workflows/release-e2e-workflow-template.yml#L71)

**Review by derek-ho — APPROVED** [review]

**Review by kavilla — APPROVED** [review]
nice!

**Pull request merged**
