### PR TITLE
add sanity test for discover and visualize and other pages

### LINKED ISSUE #11: Add test cases for "Visulization"

### PR DESCRIPTION
**Pull request by Tengda-He**
### Description
add sanity test for discover and visualize and other pages
 
### Issues Resolved
#11 #12 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Tengda-He** [comment]
attached test pass video for proof
https://user-images.githubusercontent.com/89666799/144550476-6362dad7-63f0-449b-a763-576c193ceda9.mp4

**Review by seraphjiang — APPROVED** [review]

**Comment by seraphjiang** [comment]
Could we enabled video record in GitHub action? @Tengda-He @tianleh

**Comment by tianleh** [comment]
> 

It is already enabled. See https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/1533867426

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
Notice that all the test cases are under `without-security`. Can we reuse such test cases in `with-security` (worst case: copy paste for now)? @Tengda-He

**Pull request merged**
