### PR TITLE
fix notification related eslint errors

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description

Run lint and fix complaints. Turn off the async one for now.

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seraphjiang — APPROVED** [review]

**Comment by tianleh** [comment]
Fixing the lint issue of this merged PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/206

One issue which is fixed is the missing definition of `BASE_PATH`. However, the latest test code of Notification plugin still keeps failing

https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6243355097?check_suite_focus=true

cc @seraphjiang

**Comment by tianleh** [comment]
Notification tests are failing consistently. https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6243355097?check_suite_focus=true

cc @peterzhuamazon @qreshi

**Comment by qreshi** [comment]
> Notification tests are failing consistently. https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6243355097?check_suite_focus=true
> 
> cc @peterzhuamazon @qreshi

For two of the errors, I think they're happening because the Notification Cypress tests were originally depending on the specs being run in a certain order by chance (because they were defined that way in the `cypress.json`). This is not conventional and should be changed but will require some test refactoring.

For the third failure, it's not able to find the label `data-test-subj="create-channel-description-input"` which was added in the PR that updated these tests then backported to branch `2.0`. It was passing locally so it's possible that the most recent version of Notifications is not being used here?

**Comment by tianleh** [comment]
> For the third failure, it's not able to find the label `data-test-subj="create-channel-description-input"` which was added in the PR that updated these tests then backported to branch `2.0`. It was passing locally so it's possible that the most recent version of Notifications is not being used here?

Thanks @qreshi for checking this. The latest url is parsed to build number 3015. (https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6243355097?check_suite_focus=true)

```
Run wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz
--2022-05-01 00:39:35--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz
Resolving ci.opensearch.org (ci.opensearch.org)... 52.85.61.114, 52.85.61.19, 52.85.61.96, ...
Connecting to ci.opensearch.org (ci.opensearch.org)|52.85.61.114|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/3015/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz [following]
--2022-05-01 00:39:35--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/3015/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz

```

@peterzhuamazon I think this is the build number what infra team wants OSD and plugin teams to sign off.

So, the question for Notification team is 

if `create-channel-description-input` shall be included in this release, then you may need to work with infra to trigger a new build.

Or if it shall not be included in this release, then you may need to remove the Cypress test against it.

**Comment by peterzhuamazon** [comment]
> > For the third failure, it's not able to find the label `data-test-subj="create-channel-description-input"` which was added in the PR that updated these tests then backported to branch `2.0`. It was passing locally so it's possible that the most recent version of Notifications is not being used here?
> 
> Thanks @qreshi for checking this. The latest url is parsed to build number 3015. (https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6243355097?check_suite_focus=true)
> 
> ```
> Run wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz
> --2022-05-01 00:39:35--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz
> Resolving ci.opensearch.org (ci.opensearch.org)... 52.85.61.114, 52.85.61.19, 52.85.61.96, ...
> Connecting to ci.opensearch.org (ci.opensearch.org)|52.85.61.114|:443... connected.
> HTTP request sent, awaiting response... 302 Moved Temporarily
> Location: /ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/3015/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz [following]
> --2022-05-01 00:39:35--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.0.0-rc1/3015/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.0.0-rc1-linux-x64.tar.gz
> ```
> 
> @peterzhuamazon I think this is the build number what infra team wants OSD and plugin teams to sign off.
> 
> So, the question for Notification team is
> 
> if `create-channel-description-input` shall be included in this release, then you may need to work with infra to trigger a new build.
> 
> Or if it shall not be included in this release, then you may need to remove the Cypress test against it.

OS 2695 OSD 3015 for the release candidate now.

**Comment by qreshi** [comment]
If OSD build 3015 was done before late Friday, then yeah, it won't have that label. You can edit the `'edits channels'` test in `channels.spec.js` for this repo to pass once the other tests are taken care of if we wish to proceed as-is for now.

**Comment by tianleh** [comment]
> If OSD build 3015 was done before late Friday, then yeah, it won't have that label. You can edit the `'edits channels'` test in `channels.spec.js` for this repo to pass once the other tests are taken care of if we wish to proceed as-is for now.

My intention of this PR is to just fix the eslint related issues. Also I am oncall this week and do not have additional bandwidth to handle the actual test logic. Could you help fix the third failure together with the first 2 failures? @qreshi

**Comment by tianleh** [comment]
close given https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/215

**Pull request closed without merging**
