### PR TITLE
Fix observability event analytics and notebook failing tests

### PR DESCRIPTION
**Pull request by mengweieric**
### Description

Fix observability event analytics and notebook failing tests.

```
Adding sample visualization
    ✓ Add sample observability data (10158ms)

  Testing notebooks table
    ✓ Creates a notebook and redirects to the notebook (6125ms)
    ✓ Duplicates and renames a notebook (17050ms)
    ✓ Deletes notebooks (14073ms)

  Testing paragraphs
    ✓ Goes into a notebook and creates paragraphs (15351ms)
    ✓ Renders markdown
    ✓ Shows output message (7307ms)
    ✓ Duplicates paragraphs (6804ms)
    ✓ Adds a dashboards visualization paragraph (15066ms)
    ✓ Adds a SQL query paragraph (17729ms)
    ✓ Adds a PPL query paragraph (18266ms)
    ✓ Runs all paragraphs (11655ms)
    ✓ Deletes paragraphs (13078ms)
    ✓ Cleans up test notebooks (10435ms)

  clean up all test data
    ✓ Delete visualizations from event analytics (12384ms)
    ✓ Deletes test panel (10052ms)


  16 passing (3m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        16                                                                               │
  │ Passing:      16                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     3 minutes, 8 seconds                                                             │
  │ Spec Ran:     plugins/observability-dashboards/6_notebooks.spec.js 



       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/observability-dashboards/6_      03:08       16       16        -        -        - │
  │    notebooks.spec.js                                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        03:08       16       16        -        -        - 


 Click actions
    ✓ Actions - add sample data (10748ms)

  Delete saved objects
    ✓ Delete visualizations/queries from event analytics (14666ms)


  2 passing (25s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     25 seconds                                                                       │
  │ Spec Ran:     plugins/observability-dashboards/5_event_analytics.spec.js                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /home/ubuntu/ws/opensearch-dashboards-functional-test/cypre     (1 second)
                          ss/videos/plugins/observability-dashboards/5_event_analytic               
                          s.spec.js.mp4                                                             


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/observability-dashboards/5_      00:25        2        2        -        -        - │
  │    event_analytics.spec.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:25        2        2        -        -        -  
```

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kavilla — APPROVED** [review]

**Review by ruanyl — APPROVED** [review]

**Comment by ruanyl** [comment]
@mengweieric Could you take a look at the conflicts please? Much appreciated!

**Comment by ps48** [comment]
@mengweieric @ruanyl Let's not merge this PR. The latest notebooks changes are here: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1001 as part of this PR.

**Comment by ruanyl** [comment]
> @mengweieric @ruanyl Let's not merge this PR. The latest notebooks changes are here: #1001 as part of this PR.

@ps48 Thanks for the update, shall we close this PR?

**Comment by mengweieric** [comment]
> > @mengweieric @ruanyl Let's not merge this PR. The latest notebooks changes are here: #1001 as part of this PR.
> 
> @ps48 Thanks for the update, shall we close this PR?

Please close this PR thanks.

**Pull request closed without merging**
