### PR TITLE
Apply Prettier rules to project

### PR DESCRIPTION
**Pull request by CCongWang**
### Description

* Run `npx prettier {path} --write` to fix styling issues based on prettier rules

### Issues Resolved

https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/195

### Check List

- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kavilla** [comment]
Thanks for this!

I was going to make a mention about adding a linter but we will be adding this in a subsequent PR?

**Review by kavilla — APPROVED** [review]
LGTM! Do we plan on rebasing these 7 commits or squashing and merging. If it's the latter then we should ensure a clean commit message.

**Comment by CCongWang** [comment]
> Thanks for this!
> 
> I was going to make a mention about adding a linter but we will be adding this in a subsequent PR?



> Thanks for this!
> 
> I was going to make a mention about adding a linter but we will be adding this in a subsequent PR?

yeah, I will add eslint and integrate eslint with prettier in a follow-up PR, also we plan to use husky pre-commit hook to run lint, so we can have consistent code style in every commit!

**Comment by CCongWang** [comment]
> LGTM! Do we plan on rebasing these 7 commits or squashing and merging. If it's the latter then we should ensure a clean commit message.

I guess I will squash and merge, is it the best practice? should I just click on `Squash and merge`? How to ensure a clean commit message??

**Comment by kavilla** [comment]
> > LGTM! Do we plan on rebasing these 7 commits or squashing and merging. If it's the latter then we should ensure a clean commit message.
> 
> I guess I will squash and merge, is it the best practice? should I just click on `Squash and merge`? How to ensure a clean commit message??

Probably something like "apply prettier rules to project" or anything without "conjwang" 😄

**Review by tianleh — COMMENTED** [review]
Thanks for improving the code quality for this repo!

**Pull request merged**
