### PR TITLE
Fix: flaky test on 2.14

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description

The security plugin underwent a logic change, rendering the current tenant setting code invalid. To rectify this, cy.fleshTenantSettings is being added to ensure that the tenant is properly configured, allowing all test cases to pass as they did previously.

### Issues Resolved

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6472

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Hailong-am — APPROVED** [review]

**Comment by yujin-emma** [comment]
Found the create data source failed, [tests-without-security / Run Cypress E2E tests for Core Dashboards using Bundle Snapshot (Windows)](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8984406686/job/24676168832?pr=1280#logs)

**Review by kavilla — APPROVED** [review]

**Review by yujin-emma — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Comment by kavilla** [comment]
@SuZhou-Joe do you think it's worth to wrap the new command will only reroute to home if security is enabled. to save some potentially run time of having the tests re-route to another page and back for non-security enabled?

**Comment by kavilla** [comment]
i think i will log an improvement. and can be a follow up PR for the sake of time.

**Comment by SuZhou-Joe** [comment]
> @SuZhou-Joe do you think it's worth to wrap the new command will only reroute to home if security is enabled. to save some potentially run time of having the tests re-route to another page and back for non-security enabled?

Agree, will raise one more PR to adjust that and see if I can fix the rest of the failed tests.

**Pull request merged**
