### PR TITLE
[2.0][Alerting] temp disable cypress flakey test

### PR DESCRIPTION
**Pull request by kavilla**
### Description

Copy-paste with changes that were committed from the alerting
dashboards plugin.

Source PR:
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/214

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>

### Issues Resolved

n/a

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kavilla** [comment]
@AWSHurneyt

**Comment by tianleh** [comment]
Could we create tracking issues to improve the commented tests? just want to make sure that they do have an owner and ETA. 

cc @peterzhuamazon

**Comment by AWSHurneyt** [comment]
Created this issue for the source PR. I'll reference this PR in the issue too. https://github.com/opensearch-project/alerting/issues/403

**Review by tianleh — APPROVED** [review]

**Comment by kavilla** [comment]
> Created this issue for the source PR. I'll reference this PR in the issue too. [opensearch-project/alerting#403](https://github.com/opensearch-project/alerting/issues/403)

Created a shared issue: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/183

**Pull request merged**
