### PR TITLE
[MD]Update cypress tests for sigV4 & serverless support

### LINKED ISSUE #665: [Multiple Datasource] Add functional test cases for serverless support feature

### PR DESCRIPTION
**Pull request by zhongnansu**
### Description

CI should pass once we merge PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4126

locally passed
image

### Issues Resolved

#665 

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CCongWang** [comment]
Hi @zhongnansu , could you please confirm that this PR needs to be backported to 2.x?

**Comment by zhongnansu** [comment]
> Hi @zhongnansu , could you please confirm that this PR needs to be backported to 2.x?

@CCongWang yes, it should be backported to 2.x, and release in 2.8.0.

**Comment by zhongnansu** [comment]
I don't have permission to label

**Comment by kristenTian** [comment]
LGTM！

**Review by kristenTian — APPROVED** [review]

**Comment by zhongnansu** [comment]
@CCongWang Can you help re-trigger the CI. Since https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4126 is merged, CI should pass

**Review by CCongWang — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Pull request merged**
