### PR TITLE
Fix ISM test failure

### PR DESCRIPTION
**Pull request by bowenlan-amzn**
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>

### Description

Fix the test failure, [test run](https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5425516829?check_suite_focus=true)

```
  1) Managed indices
       can have policies retried
         successfully:
     AssertionError: Timed out retrying: Expected to find content: 'Failed' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js:253:10)
```

The failure reason is we [update the cypress in our plugin repo](https://github.com/opensearch-project/index-management-dashboards-plugin/commit/5ed6c25ae769bb40d447c5e3e55fb7f89007b926#diff-9de9f25f3db58b6b6d7ad1ebbb4d33690ab9021f99bdb8361cf2697608c3847eR10-R13), but didn't sync the change to this functional test repo.

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
The other AD test failure has been fixed. If you rebase the main branch, your workflow shall be successful.

**Comment by tianleh** [comment]
Great thoughts about the development process. You can move the discussion to the main issue for wider visibility for other plugin teams. https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/72

**Comment by bowenlan-amzn** [comment]
> Great thoughts about the development process. You can move the discussion to the main issue for wider visibility for other plugin teams. #72

Have move there

**Comment by tianleh** [comment]
So exciting to see the successful run https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5428305479?check_suite_focus=true

**Review by tianleh — APPROVED** [review]
great work!

**Review by Flyingliuhub — APPROVED** [review]

**Pull request merged**
