### PR TITLE
Update vanilla snapshot test to 2.7.0 and replace deprecated set-output

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description

Update vanilla snapshot test to 2.7.0 and replace deprecated set-output

### Issues Resolved

https://github.com/opensearch-project/opensearch-build/pull/3434

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Also removed two disabled workflows that have not being used for a long time.

**Review by CCongWang — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Need to work with @RyanL1997 to fix the data table then have the version dynamically change based on `version` in package.json.

**Comment by RyanL1997** [comment]
@peterzhuamazon (cc @ananzh )
### Here are some of the findings about the failure of `data tables` test case:
**OS version 2.7 with Cypress 9**
issuesOn2 7Cy9

**OS version 2.0 with Cypress 9**
issuesOn2 0Cy9

It seems like we are missing this `paginated-table-body` for the latest OS version.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon (cc @ananzh )
> 
> **Here are some of the findings about the failure of `data tables` test case:** **OS version 2.7 with Cypress 9** issuesOn2 7Cy9
> 
> **OS version 2.0 with Cypress 9** issuesOn2 0Cy9
> 
> It seems like we are missing this `paginated-table-body` for the latest OS version.

Thanks @RyanL1997 for looking this up.
Meanwhile, I have pushed a change to auto grab the version defined in package.json.
So that this test can properly install the corresponding versions instead of hardcoding to 2.0.0 or others.

Thanks.

**Comment by kavilla** [comment]
Table fix incoming

**Pull request merged**
