### PR TITLE
Upgrade cypress to ^9.5.4

### PR DESCRIPTION
**Pull request by CCongWang**
### Description

* Upgrade Cypress to ^9.5.4

### Issues Resolved

[List any issues this PR will resolve]

### Check List

- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
Remove the prefix from the PR title "Conjwang/upgrade cypress"

**Comment by tianleh** [comment]
will monitor Alerting, Observability, Reports

**Comment by tianleh** [comment]
Reports test is successful. 

will monitor Alerting, Observability,

**Comment by tianleh** [comment]
Alerting test is successful.

will monitor Observability

**Comment by tianleh** [comment]
The only plugin left on this PR is Observability plugin which has been flaky very often. We will merge this PR so that the Cypress can be upgraded to `9.5.4`. The Docker image inside the build repo can be updated https://github.com/opensearch-project/opensearch-build/pull/2065

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
We will monitor more once Jenkins test runs. https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6237530554?check_suite_focus=true

```


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/observability-dashboards/0_      00:35        1        1        -        -        - │
  │    before.spec.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/1_      03:56        8        7        1        -        - │
  │    trace_analytics_dashboard.spec.js                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/2_      01:45        7        7        -        -        - │
  │    trace_analytics_services.spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/3_      01:24        7        7        -        -        - │
  │    trace_analytics_traces.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/4_      04:10       25       25        -        -        - │
  │    panels.spec.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/5_      08:27       36       35        1        -        - │
  │    event_analytics.spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/6_      09:14       31       30        1        -        - │
  │    notebooks.spec.js                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/7_      20:46       27       24        3        -        - │
  │    app_analytics.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/8_      273ms        1        1        -        -        - │
  │    after.spec.js                                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  4 of 9 failed (44%)                      50:21      143      137        6        -        -  
```

**Review by seraphjiang — APPROVED** [review]

**Pull request merged**
