### PR TITLE
Add AD cypress tests for uncovered workflows and pages

### PR DESCRIPTION
**Pull request by ohltyler**
### Description

This PR adds a significant amount of tests for the Anomaly Detection Dashboards plugin. Main changes include:

- [x] adding tests for:
    - [x] create detector workflow
    - [x] sample detector workflow (creating/deleting)
    - [x] real-time results
    - [x] historical analysis
    - [x] detector configuration page
    - [x] overview page
    - [x] additional filtering tests for dashboard and detector list pages
- [x] adding global utility functions including `getElementByTestId()`, and AD-specific helpers
- [x] cleaning up existing flaky tests
- [x] cleaning up existing tests by relying more on AD-controlled `data-test-subj` tags, instead of internal EUI tags
- [x] cleaning up AD-specific constants
- [x] cleaning up unused or outdated fixtures
- [x] adding test results to ingest to the test cluster

Related PR which adds the test IDs used in these tests: [link](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/183)

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
@amitgalitz @ylwu @kaituo this adds a lot of test cases for AD Dashboards - if some of you have time to take a look that would be helpful. Details in the PR description

**Comment by ohltyler** [comment]
Tests failing until related AD PR is merged first: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/183

**Comment by tianleh** [comment]
> Tests failing until related AD PR is merged first: [opensearch-project/anomaly-detection-dashboards-plugin#183](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/183)

Can we get some reviewers to approve your related PR? @ohltyler

**Comment by ohltyler** [comment]
> > Tests failing until related AD PR is merged first: [opensearch-project/anomaly-detection-dashboards-plugin#183](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/183)
> 
> Can we get some reviewers to approve your related PR? @ohltyler

I'm trying :)

**Comment by ohltyler** [comment]
AD PR merged, re-running tests now

**Review by ylwu-amzn — APPROVED** [review]

**Comment by tianleh** [comment]
@ohltyler Extended our previous conversation to a RFC https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/45

**Comment by tianleh** [comment]
We have upgraded the main branch to 1.3.0 https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/104 There are some known failures where we are working with owners to fix them. https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/104#issuecomment-1058747156

By syncing the latest main branch into your PR, you will be able to see your test results against latest 1.3.0 and address any failures related to your change in this PR.

**Review by Tengda-He — APPROVED** [review]

**Comment by ohltyler** [comment]
Rebased with `main` and all AD tests are passing:
```
      Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  plugins/anomaly-detection-dashboard      00:22        1        1        -        -        - │
  │    s-plugin/create_detector_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:24        8        8        -        -        - │
  │    s-plugin/dashboard_spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:27        5        5        -        -        - │
  │    s-plugin/detector_configuration_spe                                                         │
  │    c.js                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:31       11       11        -        -        - │
  │    s-plugin/detector_list_spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      01:20        6        6        -        -        - │
  │    s-plugin/historical_analysis_spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:21        6        6        -        -        - │
  │    s-plugin/overview_spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:20        3        3        -        -        - │
  │    s-plugin/real_time_results_spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:36        3        3        -        -        - │
  │    s-plugin/sample_detector_spec.js                                                            │
 
```

cc @tianleh @Tengda-He

**Review by tianleh — APPROVED** [review]
Great work! Looks like that this issue to have coverage report is more needed as more plugins are on this repo. https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/88

**Pull request merged**
