### PR TITLE
Cypress - version update from 9.5.4 to 12.8.1

### PR DESCRIPTION
**Pull request by jakubp-eliatra**
### Description

Cypress version update from 9.5.4. to 12.8.1, which introduces official support for cross-origin testing.

### Issues Resolved

Resolves the issue of navigating between IdP and OSD in OIDC test, also should resolve the issue of [upgrading to v11](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/408). :)

### Check List

- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
Thank you @jakubp-eliatra ! @tianleh @CCongWang @ohltyler @ashwin-pc @kavilla Could a maintainer please approve the CI to be run for this PR? 

security-dashboards-plugin requires an upgrade of Cypress to Cypress 12 which includes support for cross-origin testing which is needed for functional tests involving external IdPs. When an External IdP is used as the authentication provider of OpenSearch, the security-dashboards-plugin redirects to the login screen of the identity provider (different origin) and is redirected to OSD on successful login. In order to add functional tests for these use-cases in this repo, the version of Cypress needs to be upgraded. We currently have selenium-based functional tests in the security-dashboards-plugin repo, but would like to move them here.

See companion PR that introduces functional tests for OIDC: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/595

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Hi,

Thanks @jakubp-eliatra for the PR and @cwperks for the explanation on the purpose of this upgrade.

However, the changes are very big and the images/AMI for all integTest needs to be regenrate, and it is a very heavy process needs coordination.

Please give your thought on this: @opensearch-project/opensearch-dashboards-test 

As of now to prevent the merge breaking everything, as then current agent/runner does not have cypress12 installed yet, I will need to block this PR for a bit.

Thanks.

**Comment by peterzhuamazon** [comment]
Have offline discussion with @cwperks this is a major change that needs to be synced with build repo and ci repo.
All corresponding jenkinsfile also need changes.

Propose these steps:
1. Maintainers review the PR and have a call or whether this upgrade is ok to merge
2. Open an issue in build repo and tag me as assignee, describe the status of the PR and the ask.
3. I will raise PRs to upgrade corresponding images/amis/jenkisnfiles and merge/generate the new versions.

We can then route back to this PR and start merging.

Thanks.

**Comment by peterzhuamazon** [comment]
We need to make sure the test can be run on both x64 and arm64 architectures.
Run on LINUX/macOS/Windows platforms on the compatibility.
Thanks.

**Comment by peternied** [comment]
> I will raise PRs to upgrade corresponding images/amis/jenkisnfiles and merge/generate the new versions.

@peterzhuamazon Thanks for looking into this.  Food for thought, there was a similar scenario for build manifest specifying the docker instance name and there was an arg parameter that allowed the jdk version to be set.  When doing this upgrade if we can we source the setup/configuration from details in this repository, or move the modified elements to the test manifest future changes would be easier.

**Comment by peterzhuamazon** [comment]
> > I will raise PRs to upgrade corresponding images/amis/jenkisnfiles and merge/generate the new versions.
> 
> @peterzhuamazon Thanks for looking into this. Food for thought, there was a similar scenario for build manifest specifying the docker instance name and there was an arg parameter that allowed the jdk version to be set. When doing this upgrade if we can we source the setup/configuration from details in this repository, or move the modified elements to the test manifest future changes would be easier.

OSD is completely different from OS and that requires a much bigger overhaul.
* https://github.com/opensearch-project/opensearch-build/issues/3362

**Comment by cwperks** [comment]
@peterzhuamazon What's required to unblock this PR? Are there a list of issues somewhere that need to be complete? Happy to lend a hand to move this along so that cypress can be upgraded.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon What's required to unblock this PR? Are there a list of issues somewhere that need to be complete? Happy to lend a hand to move this along so that cypress can be upgraded.

Hi @cwperks

Just need this PR to be sorted out with the conflict files, then I will queue up the image changes in both the images and AMIs before merging this in.

Bare in mind we are currently having some issues upgrading Jenkins, so the process will take some weeks, but we can start by getting the conflicting files sorted out.

Thanks.

**Comment by cwperks** [comment]
@jakubp-eliatra Can you update this branch and resolve the conflicts with the `main` branch?

**Comment by cwperks** [comment]
@jakubp-eliatra Can you update this branch and resolve conflicts?

**Comment by peterzhuamazon** [comment]
Since there is no more activities here will replace with this one:
* https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/668

Thanks.

**Pull request closed without merging**
